### ISSUE TITLE
Relevant data fields for locked/unlocked assets are mixed up in example

### ISSUE THREAD

**Issue by troggy** [Colored-Coins/Colored-Coins-Protocol-Specification#1]
[Here](https://github.com/Colored-Coins/Colored-Coins-Protocol-Specification/wiki/Asset%20ID#example). **Public keys** are required for *unlocked* assets and **prev_tx**+**index** for *locked* while example states the opposite.

**Comment by assafshomer** [comment]
Fixed. Thanks!!
