### ISSUE TITLE
80 bytes OP_RETURNS

### ISSUE THREAD

**Issue by jspri3** [Colored-Coins/Colored-Coins-Protocol-Specification#3]
Should be 80 Bytes now. Most used client (0.11) https://getaddr.bitnodes.io/dashboard/#user-agents

"40 Bytes limit of the OP_RETURN "

**Comment by Marksmargon** [comment]
Hi, you are correct but 36% is not enough adoption for us to rely on 80 Bytes - hope in a few months

**Comment by oleiba** [comment]
Hi, these days, according to the same link, at least 81% reachable nodes use satoshi-client (or a fork of) 0.11.0 or later.
In practice, our tests shown that the time-to-confirmation for colored-coins transactions is not harmed when moving from 40 bytes to 80 (given the same fee and dust values), and they are still close to being included within the next block, on average.
Saying that, our implementation now encodes 80 byte OP_RETURN colored-coins transactions:
https://github.com/Colored-Coins/Colored-Coins-Protocol-Specification/wiki/Coloring%20Scheme#op_return
