### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by CodersBrothers** [Colored-Coins/Colored-Coins-Protocol-Specification#4]
*The company can issue a locked startup-x-to-the-moon asset with an amount of, say, 1 million units and send 25% of the issued units to the VC firm upon receiving their investment.*

in https://github.com/Colored-Coins/Colored-Coins-Protocol-Specification/wiki/Benefits
will be...

*The company can issue a locked startup-x-to-the-moon asset with an amount of, say, 10 million units and send 25% of the issued units to the VC firm upon receiving their investment.*

10, no 1. right?

**Comment by assafshomer** [comment]
Correct, thank you!
